# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-redirect-from]
hide_post_share:     true
hide_related_posts:  true

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Medium Tony's Garage"
description:	       "Vehicle guides and documentation"
author:              "Medium Tony"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
